steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Azure Resource Manager Service Connection'

    azureContainerRegistry: '{"loginServer":"usecaseb11.azurecr.io", "id" : "/subscriptions/27f7e912-b798-47fc-b008-d53d5db4b3ec/resourceGroups/AVA-EUS-ACR-MYSQL-UC-B11-RG/providers/Microsoft.ContainerRegistry/registries/UsecaseB11"}'

    dockerFile: src/adservice/Dockerfile

    additionalImageTags: adservice

steps:
- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Azure Resource Manager Service Connection'

    azureContainerRegistry: '{"loginServer":"usecaseb11.azurecr.io", "id" : "/subscriptions/27f7e912-b798-47fc-b008-d53d5db4b3ec/resourceGroups/AVA-EUS-ACR-MYSQL-UC-B11-RG/providers/Microsoft.ContainerRegistry/registries/UsecaseB11"}'

    action: 'Push an image'

    additionalImageTags: adservice
